### PR TITLE
added program page

### PR DESCRIPTION
**Pull request by tridip1931**
ref #43 
- updated nav links
- added new program page

cc: @geohacker

### CODE REVIEW

**Comment by geohacker** [comment]
@tridip1931 - thank you! This is looking good. Could you add the entire program? Some things to fix:

* We want permalinks to each day. Can perhaps just use div links? 
* We want some intro text at the top to help participants orient the schedule like https://2018.stateofthemap.org/program/. I'll share the copy but can you just put dummy text for now?

**Comment by tridip1931** [comment]
Awesome, is the program finalised, I am seeing the dummy texts in the sheet. 

>We want permalinks to each day. Can perhaps just use div links?
Yeah, div links would be better.

**Comment by geohacker** [comment]
> Awesome, is the program finalised, I am seeing the dummy texts in the sheet.

@tridip1931 you'll see the first draft in a sheet called "agenda" in the spreadsheet. We'll use this for now, and update as needed.

**Comment by tridip1931** [comment]
👍

**Comment by geohacker** [comment]
Ref #45 
@tridip1931  I took a stab:

image

I think the margins are a bit off. This seems like a better spot than replacing the twitter button on the top. What do you think?

**Comment by tridip1931** [comment]
screen shot 2018-10-09 at 10 07 08

added some margins to organizer div and cards below, is this better?

**Pull request merged**
