### PR TITLE
fix(sponsor): segregate sponsors according to categories

### PR DESCRIPTION
**Pull request by CuriousLearner**
Segregate sponsor in different categories

### CODE REVIEW

**Comment by satyaakam** [comment]
we needed various logo sizes according to categories

**Comment by tridip1931** [comment]
Thanks for the edits @CuriousLearner 
The way the architecture is, we have to edit in `.scss` file and run `npn run deploy` to write those changes to `.css`. I see you made edits directly to css file. 

Also we are using `bootstrap v4`. So we can use their classes to make those position alignments instead of writing custom ones.

**Comment by tridip1931** [comment]
cc: @geohacker

**Comment by satyaakam** [comment]
@CuriousLearner still i am seeing the Silver sponsor logo size larger than gold on the live site ?

**Comment by geohacker** [comment]
Uh oh. Yeah this is a good idea, but looks like this broke the footer. @satyaakam @CuriousLearner let's not merge anything to master because that goes live on stateofthemap.asia. If you push to `gh-pages` we can stage the changes so we don't break anything. Also getting @tridip1931's eyes is a good idea :)

Thank you for helping yay!

**Comment by CuriousLearner** [comment]
Sure, I'll make the PRs on `gh-pages` instead.

**Pull request merged**
