### PR TITLE
add partners

### PR DESCRIPTION
**Pull request by tridip1931**
👋 @geohacker 

Added logos mentioned in #34 as `Our media partners`

I was no able to find good logo for `Namma Bengaluru Foundation`. Can you ask them to provide transparent high res logo?

### CODE REVIEW

**Comment by tridip1931** [comment]
@geohacker can you check?

**Comment by tridip1931** [comment]
ping @geohacker

**Comment by geohacker** [comment]
@tridip1931 thank you! some more changes:

1. mapillary and grab are bronze
2. OpenCage and Kaart are Supporters
3. Namma bengaluru foundation is knowledge partner

**Comment by tridip1931** [comment]
So the heirarchy looks like this
Our Sponsor
Facebook
Mapbox
Mapillary Grab

Our Supporters 
OpenCage Kaart

Our knowledge partner
Namma bengaluru foundation


No MapMyIndia 
right? @geohacker

**Comment by geohacker** [comment]
@tridip1931 MapmyIndia is also supporter

**Comment by geohacker** [comment]
@tridip1931 thank you - will merge this later today after adding links.

**Pull request merged**
