### PR TITLE
added new design 

### PR DESCRIPTION
**Pull request by tridip1931**
### Next Actions
- [x] @tridip1931 to create page for COC
- [x] @tridip1931 to fix links in the website
- [x] @jinalfoflia & @geohacker to look at copy and give new copy
- [x] @jinalfoflia to give content on past SOTM

### CODE REVIEW

**Comment by tridip1931** [comment]
- [ ] Fix responsive breakage

**Comment by geohacker** [comment]
@tridip1931 apologies for the delay on this one. I've been away. I really like this approach 👍. Will push copy changes just now and apart from the feedback Tejas has https://github.com/sotm-asia/sotm-asia-2018-website/issues/32#issuecomment-389514547 this is good to go.

**Comment by jinalfoflia** [comment]
> @jinalfoflia to give content on past SOTM

Pardon me for the delay @tridip1931, will take a stab on the content by Friday.

**Comment by geohacker** [comment]
@tridip1931 thank you for your fixes. Here're few things we should do to get this MVP live:

* [ ] Make the CoC page follow the same design - background, header etc.
* [ ] Change 'Join us in Bangalore' card to may be the latest blog post? Or just hide it but we should keep the column without breaking
* [ ] Change 'Apply for Scholarships' card to 'Scholarships applications are closed now.' and remove the link. 
* [ ] In the 'become a partner' section, change 'Learn more' button to 'Download sponsorship prospectus'.
* [ ] Remove the 'Learn more' button in the venue section
* [ ] Update link for twitter on in the footer. Remove links to blog and CoC in the footer.

**Comment by tridip1931** [comment]
Did a new thing here @geohacker 
Instead of assigning a whole page for coc which comprises of only texts, I decided to show them on a modal. 

Let me know if it does not work for you. The rationale behind this is I am following general UI pattern of how TOS are displayed.

**Comment by geohacker** [comment]
> Instead of assigning a whole page for coc which comprises of only texts, I decided to show them on a modal.

I'm ok with this, but I do think it's useful to have the CoC as a page which we can link to. I just made the modal wide and added a bit more padding. If you have time we should try to keep it as a page that's consistent with rest of the site.

@tridip1931 I also noticed that the[ CSS I added to main.css](https://github.com/sotm-asia/sotm-asia-2018-website/pull/33/files#diff-23b024677d4732ee53b6d7bdc52e0fe2R2) got overridden in your last commit - do you have a build process or are all the source files committed?

I added an app.css to override some of the bootstrap css.

**Comment by geohacker** [comment]
I'm going to merge this @tridip1931. This looks like a good time to get the new design out. Thank you for all your work! 🙇

**Pull request merged**
