### PR TITLE
Add coc page

### PR DESCRIPTION
**Pull request by tridip1931**
added coc page #10

### CODE REVIEW

**Comment by geohacker** [comment]
@tridip1931 thank you! Do you think the page layout needs some work? 

image

This looks a bit non-coherent to me. With the SOTM Asia text, and the CoC prose not aligned? 

cc @rasagy

**Comment by tridip1931** [comment]
> This looks a bit non-coherent to me. With the SOTM Asia text, and the CoC prose not aligned?

Thanks for the feedback @geohacker 

This is because the `SOTM Asia text` is part of the navbar. I will change the navbar to make it more evident and separate from the main content area.

**Comment by rasagy** [comment]
@jinalfoflia Wondering if we can summarize our CoC in two lines in the beginning, and then have the complete CoC below? Would also love to see if we can break the CoC into smaller paragraphs with headings.

**Comment by jinalfoflia** [comment]
>@jinalfoflia Wondering if we can summarize our CoC in two lines in the beginning, and then have the complete CoC below? Would also love to see if we can break the CoC into smaller paragraphs with headings.

Haven't made direct changes to the PR, @rasagy can you please have your 👀 on this doc, and see if this looks fine?

https://docs.google.com/document/d/1g_WL6R1C7W7QwAdwYxFAk-77xznTJWAPeqq342u82tE/edit?usp=sharing

**Comment by rasagy** [comment]
@jinalfoflia The paragraphs read much better now! One last question: do you feel writing these as FAQ might make it easier to read?

`Who does this CoC apply to?` instead of `Persons covered by this code`
`What do you mean by harassment?` instead of `Our Anti-Harassment policy includes the following`
etc.

Let’s sync on this quickly tomorrow morning and push this live. Happy to help with the html part if needed.

**Comment by tridip1931** [comment]
closes #10

**Pull request merged**
